'use client'

import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, CheckCircle2, Clock3, Copy, ExternalLink, Heart, Instagram, Mail, Menu, MessageCircle, Play, Search, Sparkles, Star, X, Youtube, Zap } from 'lucide-react'

type Video={id:string;title:string;published:string;thumbnail:string;url:string;views?:number;duration?:number;short?:boolean}
type Data={channelId:string;videos:Video[];subscribers:number;totalViews?:number}

const HANDLE='@manishafamilychannel2859'
const CHANNEL_URL='https://youtube.com/@manishafamilychannel2859'
const WA='https://wa.me/917634973984?text=Hello%20Manisha%20Family%20Channel%2C%20I%20need%20support'
const UPI='7634973984@fam'
const PACKAGES=[
 ['Product Review / Unboxing','A dedicated review or unboxing built around your product.','5–10 min','Contact us'],
 ['Product Integration in Video','Natural product placement inside a family-vlog episode.','30–90 sec','Contact us'],
 ['Dedicated Video Promotion','A complete sponsored video focused on your brand or product.','5–12 min','Contact us'],
 ['YouTube Shorts Promotion','Short-form promotion designed for quick reach and discovery.','15–60 sec','Contact us'],
 ['Community Post Promotion','A featured community post with your campaign message.','24–48 hrs','Contact us'],
 ['Banner / Logo Placement','Brand visibility through website or video artwork placement.','7–30 days','Contact us'],
 ['Shoutout / Mention','A friendly brand mention within a regular upload.','10–30 sec','Contact us'],
 ['Sponsored Segment','A polished sponsored segment integrated into an episode.','60–180 sec','Contact us'],
 ['Social Media Promotion','Cross-platform promotional support for your campaign.','Custom','Contact us'],
 ['Custom Promotion Package','Tell us your goal and we will build a package around it.','Custom','Contact us'],
]

function formatNumber(n:number){return new Intl.NumberFormat('en-IN',{notation:n>999999?'compact':'standard',maximumFractionDigits:1}).format(n)}
function timeAgo(date:string){const d=Date.now()-new Date(date).getTime();const days=Math.floor(d/86400000);if(days<1)return 'Today';if(days<30)return `${days}d ago`;if(days<365)return `${Math.floor(days/30)}mo ago`;return `${Math.floor(days/365)}y ago`}
function upiLink(amount:string){return `upi://pay?pa=${encodeURIComponent(UPI)}&pn=${encodeURIComponent('Manisha Family Channel')}&am=${encodeURIComponent(amount)}&cu=INR`}
function qrLink(amount:string){return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(upiLink(amount))}`}

export default function Home(){
 const [page,setPage]=useState('home'); const [menu,setMenu]=useState(false); const [data,setData]=useState<Data>({channelId:'',videos:[],subscribers:0}); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [filter,setFilter]=useState('all'); const [selected,setSelected]=useState<Video|null>(null); const [amount,setAmount]=useState('101'); const [copied,setCopied]=useState(false); const [formSent,setFormSent]=useState(false)
 const shorts=useMemo(()=>data.videos.filter(v=>v.short),[data.videos]); const videos=useMemo(()=>data.videos.filter(v=>!v.short),[data.videos]);
 const filtered=useMemo(()=>videos.filter(v=>v.title.toLowerCase().includes(search.toLowerCase()) && (filter==='all'||(filter==='recent'&&Date.now()-new Date(v.published).getTime()<30*86400000))),[videos,search,filter])
 const go=(p:string)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})}
 useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch('/api/youtube',{cache:'no-store'});const j=await r.json();if(alive)setData(j)}catch{}finally{if(alive)setLoading(false)}};load();const id=setInterval(load,1800000);return()=>{alive=false;clearInterval(id)}},[])
 useEffect(()=>{const tick=async()=>{try{const r=await fetch('/api/subscribers',{cache:'no-store'});const j=await r.json();if(j.subscribers)setData(d=>({...d,subscribers:j.subscribers}))}catch{}};tick();const id=setInterval(tick,30000);return()=>clearInterval(id)},[])
 const nav=[['home','Home'],['videos','Videos'],['shorts','Shorts'],['promote','Promote With Us'],['donate','Donate'],['about','About & Contact']]
 return <div className="min-h-screen bg-[#090611] text-white">
  <header className="sticky top-0 z-50 border-b border-white/10 bg-[#090611]/75 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3">
   <button onClick={()=>go('home')} className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-pink-500 via-purple-500 to-orange-400 shadow-lg shadow-pink-500/20"><Heart fill="white" size={21}/></div><div className="text-left"><div className="font-black tracking-tight">Manisha Family</div><div className="text-[11px] text-white/50">CHANNEL</div></div></button>
   <nav className="hidden items-center gap-1 lg:flex">{nav.map(([id,label])=><button key={id} onClick={()=>go(id)} className={`rounded-full px-4 py-2 text-sm transition ${page===id?'bg-white text-black':'text-white/70 hover:bg-white/10 hover:text-white'}`}>{label}</button>)}</nav>
   <div className="hidden items-center gap-3 sm:flex"><div className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-pink-400 shadow-[0_0_12px_#f472b6]"/>{formatNumber(data.subscribers)} subscribers</div><a href={CHANNEL_URL} target="_blank" className="rounded-full bg-white px-4 py-2 text-sm font-bold text-black">YouTube <ExternalLink className="ml-1 inline" size={14}/></a></div>
   <button onClick={()=>setMenu(!menu)} className="rounded-xl border border-white/10 p-2 lg:hidden">{menu?<X/>:<Menu/>}</button>
  </div>{menu&&<div className="border-t border-white/10 px-5 py-3 lg:hidden">{nav.map(([id,label])=><button key={id} onClick={()=>go(id)} className="block w-full rounded-xl px-4 py-3 text-left text-white/80 hover:bg-white/10">{label}</button>)}</div>}</header>

  <AnimatePresence mode="wait"><motion.main key={page} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.22}}>
   {page==='home'&&<HomePage data={data} loading={loading} go={go} />}
   {page==='videos'&&<VideosPage videos={filtered} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} loading={loading} onOpen={setSelected}/>} 
   {page==='shorts'&&<ShortsPage shorts={shorts} loading={loading} onOpen={setSelected}/>} 
   {page==='promote'&&<PromotePage/>}
   {page==='donate'&&<DonatePage amount={amount} setAmount={setAmount} copied={copied} setCopied={setCopied}/>} 
   {page==='about'&&<AboutPage formSent={formSent} setFormSent={setFormSent}/>} 
  </motion.main></AnimatePresence>

  <a href={WA} target="_blank" aria-label="WhatsApp support" className="fixed bottom-5 right-5 z-50 grid h-14 w-14 place-items-center rounded-full bg-[#25D366] text-white shadow-2xl shadow-green-500/25 transition hover:scale-110"><MessageCircle fill="white" size={27}/></a>
  <AnimatePresence>{selected&&<motion.div className="fixed inset-0 z-[60] grid place-items-center bg-black/80 p-5 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)}><motion.div onClick={e=>e.stopPropagation()} initial={{scale:.95,y:10}} animate={{scale:1,y:0}} className="glass w-full max-w-3xl overflow-hidden rounded-3xl"><div className="relative aspect-video bg-black"><iframe className="h-full w-full" src={`https://www.youtube.com/embed/${selected.id}?autoplay=1`} title={selected.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/><button onClick={()=>setSelected(null)} className="absolute right-3 top-3 rounded-full bg-black/70 p-2"><X/></button></div><div className="p-5"><h3 className="font-bold">{selected.title}</h3><a href={selected.url} target="_blank" className="mt-3 inline-flex items-center gap-2 text-sm text-pink-300">Open on YouTube <ExternalLink size={15}/></a></div></motion.div></motion.div>}</AnimatePresence>
 </div>
}

function HomePage({data,loading,go}:{data:Data;loading:boolean;go:(p:string)=>void}){return <>
 <section className="relative overflow-hidden"><div className="hero-grid absolute inset-0 opacity-70"/><div className="absolute -left-20 top-20 h-72 w-72 rounded-full bg-pink-500/20 blur-3xl float"/><div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-purple-500/20 blur-3xl float2"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:pt-28">
  <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/70"><Sparkles size={15} className="text-pink-300"/> Welcome to our family corner</div><h1 className="max-w-4xl text-5xl font-black leading-[.98] tracking-[-.04em] sm:text-7xl">Life, laughter & <span className="gradient-text">family moments.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/60">Welcome to <b className="text-white">Manisha Family Channel</b> — a warm place for family vlogs, fun Shorts, memories and stories worth sharing.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>go('videos')} className="glow rounded-full bg-gradient-to-r from-pink-500 via-purple-500 to-orange-400 px-6 py-3.5 font-bold transition hover:scale-105"><Play className="mr-2 inline" size={17} fill="white"/> Watch Videos</button><button onClick={()=>go('shorts')} className="rounded-full border border-white/15 bg-white/5 px-6 py-3.5 font-bold hover:bg-white/10">Watch Shorts <ArrowRight className="ml-2 inline" size={17}/></button></div><div className="mt-8 flex flex-wrap gap-3"><a href={WA} target="_blank" className="rounded-full bg-[#25D366]/15 px-5 py-3 text-sm font-semibold text-green-300 hover:bg-[#25D366]/25"><MessageCircle className="mr-2 inline" size={16}/> WhatsApp Support</a><button onClick={()=>go('donate')} className="rounded-full bg-pink-500/15 px-5 py-3 text-sm font-semibold text-pink-200 hover:bg-pink-500/25">❤️ Support the Channel</button></div></div>
  <div className="relative"><div className="glass pulse-glow relative mx-auto max-w-md rounded-[2rem] p-3"><div className="noise relative aspect-[4/5] overflow-hidden rounded-[1.5rem] bg-gradient-to-br from-pink-500/80 via-purple-600/70 to-orange-400/70"><div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_20%,rgba(255,255,255,.3),transparent_30%),radial-gradient(circle_at_80%_75%,rgba(255,255,255,.2),transparent_25%)]"/><div className="absolute left-6 top-6 rounded-2xl border border-white/20 bg-black/20 px-4 py-3 backdrop-blur-md"><div className="text-xs text-white/70">LIVE COMMUNITY</div><div className="text-xl font-black">{formatNumber(data.subscribers)}+</div><div className="text-xs text-white/60">subscribers</div></div><div className="absolute bottom-6 left-6 right-6 rounded-3xl border border-white/20 bg-black/25 p-5 backdrop-blur-md"><div className="text-sm text-white/70">Manisha Family Channel</div><div className="mt-1 text-3xl font-black">Together is our favourite place.</div></div><div className="absolute right-6 top-28 grid h-20 w-20 place-items-center rounded-full bg-white/15 backdrop-blur-md"><Heart fill="white" size={32}/></div></div></div></div>
 </div></section>
 <section className="mx-auto max-w-7xl px-5 pb-20"><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<Youtube/>} label="Subscribers" value={loading?'—':formatNumber(data.subscribers)}/><Stat icon={<Play/>} label="Latest uploads" value={loading?'—':String(data.videos.length)}/><Stat icon={<Zap/>} label="Auto refresh" value="30m / 30s"/></div></section>
 <section className="mx-auto max-w-7xl px-5 pb-24"><div className="mb-8 flex items-end justify-between gap-4"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-pink-300">Latest</div><h2 className="mt-2 text-3xl font-black sm:text-4xl">Fresh from the channel</h2></div><button onClick={()=>go('videos')} className="hidden rounded-full border border-white/10 px-4 py-2 text-sm sm:block">See all <ArrowRight className="ml-1 inline" size={15}/></button></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{data.videos.slice(0,4).map(v=><VideoCard key={v.id} v={v} onOpen={()=>{}} compact/>)}</div></section>
 </>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="glass rounded-3xl p-5"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 text-pink-300">{icon}</div><div className="text-2xl font-black">{value}</div><div className="mt-1 text-sm text-white/50">{label}</div></div>}
function VideoCard({v,onOpen,compact=false}:{v:Video;onOpen:()=>void;compact?:boolean}){return <article className={`glass group overflow-hidden rounded-3xl transition hover:-translate-y-1 hover:border-white/20 ${compact?'':'h-full'}`}><button onClick={onOpen} className="block w-full text-left"><div className="relative aspect-video overflow-hidden bg-white/5"><img src={v.thumbnail} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 grid place-items-center bg-black/0 transition group-hover:bg-black/25"><span className="scale-75 rounded-full bg-white p-4 text-black opacity-0 shadow-xl transition group-hover:scale-100 group-hover:opacity-100"><Play fill="currentColor" size={20}/></span></div></div><div className="p-4"><h3 className={`font-bold leading-6 ${compact?'line-clamp-2':''}`}>{v.title}</h3><div className="mt-3 flex items-center justify-between text-xs text-white/45"><span>{timeAgo(v.published)}</span><span>{v.views?formatNumber(v.views)+' views':'YouTube'}</span></div></div></button></article>}

function VideosPage({videos,search,setSearch,filter,setFilter,loading,onOpen}:{videos:Video[];search:string;setSearch:(s:string)=>void;filter:string;setFilter:(s:string)=>void;loading:boolean;onOpen:(v:Video)=>void}){return <section className="mx-auto max-w-7xl px-5 py-12 sm:py-16"><PageIntro eyebrow="Videos" title="Every upload, in one place." text="Fresh uploads are pulled automatically from the channel RSS feed."/><div className="mt-8 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-white/40" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search videos..." className="glass w-full rounded-2xl py-3.5 pl-11 pr-4 outline-none placeholder:text-white/35 focus:border-pink-400/50"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="glass rounded-2xl px-4 py-3.5 outline-none"><option value="all" className="bg-[#15101f]">All uploads</option><option value="recent" className="bg-[#15101f]">Last 30 days</option></select></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{loading?[1,2,3,4,5,6].map(i=><div key={i} className="glass aspect-video animate-pulse rounded-3xl"/>):videos.length?videos.map(v=><VideoCard key={v.id} v={v} onOpen={()=>onOpen(v)}/>):<Empty text="No videos found for this search."/>}</div></section>}
function ShortsPage({shorts,loading,onOpen}:{shorts:Video[];loading:boolean;onOpen:(v:Video)=>void}){return <section className="mx-auto max-w-7xl px-5 py-12 sm:py-16"><PageIntro eyebrow="Shorts" title="Quick moments. Big smiles." text="A mobile-first reel wall for the latest Shorts uploaded to the channel."/><div className="mt-10 flex snap-x gap-5 overflow-x-auto pb-8 hide-scrollbar">{loading?[1,2,3].map(i=><div key={i} className="min-w-[280px] max-w-[360px] flex-1 aspect-[9/16] animate-pulse rounded-[2rem] bg-white/5"/>):shorts.length?shorts.map(v=><button key={v.id} onClick={()=>onOpen(v)} className="reel group relative min-w-[280px] max-w-[360px] flex-1 overflow-hidden rounded-[2rem] border border-white/10 bg-black text-left shadow-2xl"><img src={v.thumbnail} alt="" className="aspect-[9/16] h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black/10"/><div className="absolute bottom-0 p-5"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-pink-500/80 px-3 py-1 text-xs font-bold"><Play size={12} fill="white"/> SHORT</div><h3 className="text-lg font-bold leading-6">{v.title}</h3><div className="mt-2 text-xs text-white/60">{timeAgo(v.published)}</div></div></button>):<Empty text="No Shorts detected yet. Uploads will appear automatically."/>}</div></section>}
function PromotePage(){return <section className="mx-auto max-w-7xl px-5 py-12 sm:py-16"><PageIntro eyebrow="Promote With Us" title="Put your brand in front of our family audience." text="Choose a promotion format or message us for a custom campaign. Pricing is shared on WhatsApp."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{PACKAGES.map(([title,desc,duration,price])=><div key={title} className="glass group rounded-3xl p-6 transition hover:-translate-y-1 hover:border-pink-400/30"><div className="mb-5 flex items-center justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-pink-500/20 to-purple-500/20"><Star size={20} className="text-pink-300"/></div><span className="text-xs text-white/40">{duration}</span></div><h3 className="text-xl font-black">{title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-white/55">{desc}</p><div className="mt-6 flex items-center justify-between"><span className="font-semibold text-white/70">{price}</span><a target="_blank" href={`https://wa.me/917634973984?text=${encodeURIComponent(`Hello, I want to book "${title}" promotion package`)}`} className="rounded-full bg-white px-4 py-2 text-sm font-bold text-black transition hover:bg-pink-100">Book Now</a></div></div>)}</div></section>}
function DonatePage({amount,setAmount,copied,setCopied}:{amount:string;setAmount:(s:string)=>void;copied:boolean;setCopied:(b:boolean)=>void}){const copy=async()=>{await navigator.clipboard?.writeText(UPI);setCopied(true);setTimeout(()=>setCopied(false),1600)};return <section className="mx-auto max-w-5xl px-5 py-12 sm:py-16"><PageIntro eyebrow="Support the channel" title="Every bit of support means a lot. ❤️" text="Use your preferred UPI app on mobile, or scan the QR code from another device."/><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="glass rounded-[2rem] p-6 sm:p-8"><div className="text-sm text-white/50">Donation UPI ID</div><button onClick={copy} className="mt-2 flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4 text-left"><span className="font-mono text-lg">{UPI}</span>{copied?<CheckCircle2 className="text-green-300"/>:<Copy className="text-white/50"/>}</button><div className="mt-8 text-sm font-semibold">Choose amount</div><div className="mt-3 grid grid-cols-3 gap-2 sm:grid-cols-5">{['51','101','251','501','1000'].map(a=><button key={a} onClick={()=>setAmount(a)} className={`rounded-xl border py-3 font-bold ${amount===a?'border-pink-400 bg-pink-500/20 text-pink-200':'border-white/10 bg-white/5 hover:bg-white/10'}`}>₹{a}</button>)}</div><div className="mt-4"><label className="text-xs text-white/45">Custom amount</label><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} className="glass mt-2 w-full rounded-2xl p-4 outline-none" placeholder="Enter amount"/></div><a href={amount&&Number(amount)>0?upiLink(amount):'#'} className="glow mt-6 flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-pink-500 to-orange-400 py-4 font-black transition hover:scale-[1.01]">Donate ₹{amount||'0'} <ArrowRight size={18}/></a><p className="mt-3 text-center text-xs text-white/40">On mobile, your device may open a supported UPI app.</p></div><div className="glass rounded-[2rem] p-6 text-center"><div className="text-sm font-semibold">Scan to pay</div><div className="mx-auto mt-5 aspect-square max-w-[280px] overflow-hidden rounded-2xl bg-white p-3"><img src={qrLink(amount||'101')} alt="UPI QR code" className="h-full w-full"/></div><div className="mt-4 text-xs text-white/45">QR updates automatically with your amount.</div></div></div></section>}
function AboutPage({formSent,setFormSent}:{formSent:boolean;setFormSent:(b:boolean)=>void}){return <section className="mx-auto max-w-6xl px-5 py-12 sm:py-16"><PageIntro eyebrow="About & Contact" title="A family channel made with heart." text="Manisha Family Channel shares everyday family moments, vlogs, celebrations and fun short-form content."/><div className="mt-10 grid gap-6 lg:grid-cols-2"><div className="glass rounded-[2rem] p-7 sm:p-9"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-pink-500 to-orange-400"><Heart fill="white"/></div><h2 className="mt-6 text-2xl font-black">Let's stay connected</h2><p className="mt-3 leading-7 text-white/55">For support, collaborations, promotion packages or general questions, reach out directly. We are happy to hear from you.</p><div className="mt-7 space-y-3"><a href={WA} target="_blank" className="block rounded-2xl bg-[#25D366]/15 p-4 text-green-200">WhatsApp: +91 7634973984</a><a href={CHANNEL_URL} target="_blank" className="block rounded-2xl bg-red-500/15 p-4 text-red-200">YouTube: {HANDLE}</a><div className="flex gap-3"><a href={CHANNEL_URL} target="_blank" className="grid h-12 w-12 place-items-center rounded-xl bg-white/5 hover:bg-white/10"><Youtube/></a><a href="#" className="grid h-12 w-12 place-items-center rounded-xl bg-white/5 hover:bg-white/10"><Instagram/></a></div></div></div><form onSubmit={e=>{e.preventDefault();setFormSent(true)}} className="glass rounded-[2rem] p-7 sm:p-9"><div className="text-sm font-bold text-pink-300">CONTACT FORM</div><h2 className="mt-2 text-2xl font-black">Send a message</h2>{formSent?<div className="mt-8 rounded-2xl bg-green-500/10 p-5 text-green-200"><CheckCircle2 className="mb-2"/>Thanks! Your message is ready to be followed up via the channel contact.</div>:<><input required placeholder="Your name" className="glass mt-6 w-full rounded-2xl p-4 outline-none"/><input required type="email" placeholder="Email address" className="glass mt-3 w-full rounded-2xl p-4 outline-none"/><textarea required placeholder="Your message" rows={6} className="glass mt-3 w-full rounded-2xl p-4 outline-none"/><button className="mt-4 w-full rounded-2xl bg-white py-4 font-black text-black">Send message <ArrowRight className="ml-1 inline" size={17}/></button></>}</form></div></section>}
function PageIntro({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="max-w-3xl"><div className="text-sm font-bold uppercase tracking-[.2em] text-pink-300">{eyebrow}</div><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">{title}</h1><p className="mt-5 text-lg leading-8 text-white/55">{text}</p></div>}
function Empty({text}:{text:string}){return <div className="glass col-span-full rounded-3xl p-10 text-center text-white/50">{text}</div>}
